name: Deploy to AWS Amplify

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  AWS_REGION: us-east-2
  AMPLIFY_APP_NAME: sentinel-web

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to Amplify
      run: |
        echo "Starting deployment to Amplify..."
        
        # Get the app details
        echo "Searching for app: ${{ env.AMPLIFY_APP_NAME }}"
        
        # Get all apps and filter by name
        APPS_JSON=$(aws amplify list-apps --region us-east-2 --output json)
        echo "All apps: $APPS_JSON"
        
        # Extract the first app ID for the specific name
        APP_ID=$(echo "$APPS_JSON" | jq -r ".apps[] | select(.name == \"${{ env.AMPLIFY_APP_NAME }}\") | .appId" | head -1)
        
        echo "Extracted app ID: '$APP_ID'"
        
        if [ "$APP_ID" = "null" ] || [ -z "$APP_ID" ] || [ "$APP_ID" = "None" ]; then
          echo "Error: App '${{ env.AMPLIFY_APP_NAME }}' not found!"
          echo "Available apps:"
          aws amplify list-apps --region us-east-2 --query "apps[].{Name:name,ID:appId}" --output table
          exit 1
        fi
        
        echo "Found app ID: $APP_ID"
        
        # Start the build job
        echo "Starting build job..."
        aws amplify start-job \
          --app-id $APP_ID \
          --branch-name main \
          --job-type RELEASE \
          --region us-east-2
        
        echo "Deployment job started successfully!"
        echo "App ID: $APP_ID"
        echo "Branch: main"
        echo "Job Type: RELEASE"

    - name: Deploy status
      run: |
        echo "Deployment initiated successfully!"
        echo "Check AWS Amplify console for deployment status"
