name: Deploy to AWS Amplify

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  AWS_REGION: us-east-2
  AMPLIFY_APP_NAME: sentinel-web

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to Amplify
      run: |
        echo "Starting deployment to Amplify..."
        
        # Check if app exists
        echo "Checking if app '${{ env.AMPLIFY_APP_NAME }}' exists..."
        APPS_JSON=$(aws amplify list-apps --region us-east-2 --output json)
        EXISTING_APP=$(echo "$APPS_JSON" | jq -r ".apps[] | select(.name == \"${{ env.AMPLIFY_APP_NAME }}\") | .appId" | head -1)
        
        if [ -n "$EXISTING_APP" ] && [ "$EXISTING_APP" != "null" ] && [ "$EXISTING_APP" != "None" ]; then
          echo "Found existing app with ID: '$EXISTING_APP'"
          echo "Checking if it's Git-connected..."
          
          # Check if app has repository connection
          APP_CONFIG=$(aws amplify get-app --app-id $EXISTING_APP --region us-east-2 --output json)
          REPO_URL=$(echo "$APP_CONFIG" | jq -r '.app.repository')
          
          if [ "$REPO_URL" = "null" ] || [ -z "$REPO_URL" ]; then
            echo "Existing app is not Git-connected. Deleting it to recreate properly..."
            
            # Delete existing app
            aws amplify delete-app --app-id $EXISTING_APP --region us-east-2
            echo "Existing app deleted successfully"
            
            # Wait for deletion to complete
            echo "Waiting for app deletion to complete..."
            sleep 30
            
            EXISTING_APP=""
          else
            echo "App is already Git-connected to: $REPO_URL"
          fi
        fi
        
        if [ -z "$EXISTING_APP" ] || [ "$EXISTING_APP" = "null" ] || [ "$EXISTING_APP" = "None" ]; then
          echo "Creating new Git-connected Amplify app..."
          
          # Create new app from GitHub repository
          aws amplify create-app \
            --name ${{ env.AMPLIFY_APP_NAME }} \
            --repository "https://github.com/jamie-humareso/SentinelPayWebsite" \
            --platform "WEB" \
            --region us-east-2 \
            --description "Sentinel Pay Analytics Platform"
          
          echo "App created successfully!"
          echo "Now you need to connect the branch in the AWS Amplify console:"
          echo "1. Go to AWS Amplify Console: https://console.aws.amazon.com/amplify/home?region=us-east-2"
          echo "2. Select the app: ${{ env.AMPLIFY_APP_NAME }}"
          echo "3. Click 'Connect branch'"
          echo "4. Select 'main' branch"
          echo "5. Amplify will automatically build and deploy using amplify.yml"
        fi
        
        echo ""
        echo "Next steps:"
        echo "1. Go to AWS Amplify Console: https://console.aws.amazon.com/amplify/home?region=us-east-2"
        echo "2. Select your app: ${{ env.AMPLIFY_APP_NAME }}"
        echo "3. Connect the main branch if not already connected"
        echo "4. Amplify will automatically build and deploy on future pushes"
        echo "5. Your site will be available at: https://${{ env.AMPLIFY_APP_NAME }}.amplifyapp.com"

    - name: Deploy status
      run: |
        echo "Deployment process completed!"
        echo "Check AWS Amplify console for next steps"
        echo "Your site will be available at: https://${{ env.AMPLIFY_APP_NAME }}.amplifyapp.com"
