name: Deploy to AWS Amplify

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  AWS_REGION: us-east-2
  AMPLIFY_APP_NAME: sentinel-web

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to Amplify
      run: |
        echo "Starting deployment to Amplify..."
        
        # Check if app exists
        echo "Checking if app '${{ env.AMPLIFY_APP_NAME }}' exists..."
        APPS_JSON=$(aws amplify list-apps --region us-east-2 --output json)
        EXISTING_APP=$(echo "$APPS_JSON" | jq -r ".apps[] | select(.name == \"${{ env.AMPLIFY_APP_NAME }}\") | .appId" | head -1)
        
        echo "Found app ID: '$EXISTING_APP'"
        
        if [ -z "$EXISTING_APP" ] || [ "$EXISTING_APP" = "null" ] || [ "$EXISTING_APP" = "None" ]; then
          echo "App not found. Creating new Amplify app from GitHub repository..."
          
          # Create new app from GitHub repository
          aws amplify create-app \
            --name ${{ env.AMPLIFY_APP_NAME }} \
            --repository "https://github.com/jamie-humareso/SentinelPayWebsite" \
            --platform "WEB" \
            --region us-east-2 \
            --description "Sentinel Pay Analytics Platform"
          
          echo "App created successfully!"
          echo "Now you need to connect the branch in the AWS Amplify console:"
          echo "1. Go to AWS Amplify Console"
          echo "2. Select the app: ${{ env.AMPLIFY_APP_NAME }}"
          echo "3. Click 'Connect branch'"
          echo "4. Select 'main' branch"
          echo "5. Amplify will automatically build and deploy"
        else
          echo "App already exists with ID: $EXISTING_APP"
          echo "Checking if it's connected to repository..."
          
          # Check if app has branches
          BRANCHES=$(aws amplify list-branches --app-id $EXISTING_APP --region us-east-2 --query "branches[].branchName" --output text)
          
          if [ -z "$BRANCHES" ] || [ "$BRANCHES" = "None" ]; then
            echo "App exists but has no branches. Please connect the main branch in AWS Amplify console."
            echo "1. Go to AWS Amplify Console"
            echo "2. Select the app: ${{ env.AMPLIFY_APP_NAME }}"
            echo "3. Click 'Connect branch'"
            echo "4. Select 'main' branch"
          else
            echo "App has branches: $BRANCHES"
            echo "Checking if main branch exists..."
            
            if echo "$BRANCHES" | grep -q "main"; then
              echo "Main branch exists. Triggering build..."
              aws amplify start-job \
                --app-id $EXISTING_APP \
                --branch-name main \
                --job-type RELEASE \
                --region us-east-2
              
              echo "Build job started successfully!"
            else
              echo "Main branch not found. Please connect it in AWS Amplify console."
            fi
          fi
        fi
        
        echo ""
        echo "Next steps:"
        echo "1. Go to AWS Amplify Console: https://console.aws.amazon.com/amplify/home?region=us-east-2"
        echo "2. Select your app: ${{ env.AMPLIFY_APP_NAME }}"
        echo "3. Connect the main branch if not already connected"
        echo "4. Amplify will automatically build and deploy on future pushes"

    - name: Deploy status
      run: |
        echo "Deployment process completed!"
        echo "Check AWS Amplify console for next steps"
        echo "Your site will be available at: https://${{ env.AMPLIFY_APP_NAME }}.amplifyapp.com"
